---
title: "Pilot analysis"
output: html_notebook
---


```{r}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```


```{r}
library(dplyr)
library(tidyr)
library(langcog)
library(ggplot2)
library(ggthemes)
library(forcats)
library(knitr)
theme_set(theme_few())
data.path <- "~/Documents/research/causals/data/pilots/"

readData <- function(filename){
  return(read.csv(paste(data.path, filename, sep = "")))
}
```

# Pilot 1

```{r}
d.info <- readData("pilot-causals-1-subject_information.csv")
```


```{r}
d <- readData("pilot-causals-1-trials.csv")
```

## Time

Total time spent on experiment

```{r fig.width=5}
d %>% 
  group_by(workerid) %>% 
  summarize(totalMin = sum(rt/1000/60)) %>%
  ggplot(., aes(x = totalMin))+
  geom_histogram()
```

Time on each trial (first trial in red)

```{r fig.width=5}
d %>%
  ggplot(., aes(x = rt / 1000, fill = trial_num == 0))+
  geom_histogram(position = position_dodge())+
  scale_fill_solarized()+
  xlab("seconds")+
  xlim(0, 200)
```

## Prior questions

```{r fig.width=5.0, fig.height = 6}
d %>% 
  select(story, target, distribution, starts_with("prior")) %>%
  gather(key, val, starts_with("prior")) %>%
  separate(key, into = c("key", "question")) %>%
  mutate(question = fct_relevel(question, "probabilityOfPresent"),
         distribution = fct_relevel(distribution, "rare", "accidental", "gendered", "female", "prevalent", "biological")) %>%
  ggplot(., aes( x = val, fill = distribution))+
  geom_histogram()+
  facet_grid(distribution~question)+
  theme(strip.text.y = element_text(angle = 0))+
  scale_fill_solarized()+
  guides(fill = F)
```

## Listener data

```{r fig.width=8, fig.height = 3}
d %>% 
  filter(condition == "listener") %>%
  select(story, target, distribution, posterior) %>%
  mutate(distribution = fct_relevel(distribution, "rare", "accidental", "gendered", "female", "prevalent", "biological")) %>%
  ggplot(., aes( x = posterior, fill = distribution))+
  geom_histogram()+
  facet_grid(.~distribution)+
  #theme(strip.text.y = element_text(angle = 0))+
  scale_fill_solarized()+
  guides(fill = F)+
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1))
```



### Compare listener and prior prevalenceWhenPresent

```{r}
d.listener.prior <- d %>% 
  filter(condition == "listener") %>%
  select(story, target, distribution, prior_prevalenceGivenPresent, posterior) %>%
  gather(key, val, prior_prevalenceGivenPresent, posterior) %>%
  mutate(distribution = fct_relevel(distribution, "rare", "accidental", "gendered", "female", "prevalent", "biological")) %>%
  group_by(distribution, key) %>%
  multi_boot_standard(column = "val")

d.listener.prior %>%
  select(-ci_lower, -ci_upper) %>%
  spread(key, mean) %>%
  ungroup() %>%
  summarize(correlation = cor(prior_prevalenceGivenPresent, posterior))

left_join(
  d.listener.prior %>%
    filter(key == "posterior") %>%
    rename(listener = mean, 
           listener_upper = ci_upper, listener_lower = ci_lower) %>%
    select(-key),
  d.listener.prior %>%
    filter(key == "prior_prevalenceGivenPresent") %>%
    rename(prior = mean, 
           prior_upper = ci_upper, prior_lower = ci_lower) %>%
    select(-key)
  ) %>%
  ggplot(., aes( x = prior, xmin = prior_lower, xmax =prior_upper,
                 y = listener, ymin = listener_lower, ymax = listener_upper,
                 color = distribution))+
  geom_abline(intercept = 0, slope = 1, lty = 3)+
  geom_linerange()+
  geom_errorbarh(width = 0.1)+
  geom_point()+
  xlim(0, 1)+
  ylim(0, 1)+
  coord_fixed()+
  scale_color_solarized()
```

## Speaker data


```{r}
d %>% 
  filter(condition == "speaker", frequency %in% c(10)) %>%
  mutate(distribution = fct_relevel(distribution, "rare", "accidental", "gendered", "female", "prevalent", "biological")) %>%
  group_by(distribution, frequency) %>%
  summarize(n = n()) %>%
  kable()
```


```{r}
d %>% 
  filter(condition == "speaker", frequency %in% c(30)) %>%
  mutate(distribution = fct_relevel(distribution, "rare", "accidental", "gendered", "female", "prevalent", "biological")) %>%
  group_by(distribution, frequency) %>%
  summarize(n = n()) %>%
  kable()
```
```{r}
d %>% 
  filter(condition == "speaker", frequency %in% c(50)) %>%
  mutate(distribution = fct_relevel(distribution, "rare", "accidental", "gendered", "female", "prevalent", "biological")) %>%
  group_by(distribution, frequency) %>%
  summarize(n = n()) %>%
  kable()
```

```{r fig.width = 8, fig.height = 3.5}
d %>% 
  filter(condition == "speaker") %>%
  mutate(distribution = fct_relevel(distribution, "rare", "accidental", "gendered", "female", "prevalent", "biological")) %>%
  group_by(distribution, frequency) %>% #also, by story / target
  multi_boot_standard(column = "posterior") %>%
  ggplot(., aes( x = frequency, y = mean, ymin = ci_lower, ymax = ci_upper, group = distribution, fill = distribution))+
  geom_bar(stat='identity', position = position_dodge(), color = 'black')+
  geom_errorbar()+
  scale_fill_solarized()+
  scale_x_continuous(breaks = c(10, 30, 50, 70))+
  facet_grid(.~distribution)+
  guides(fill = F)+
  ylab("proportion agree with causal")
```
# Pilot 2

```{r}
d.info <- readData("pilot-causals-2-subject_information.csv")
```


```{r}
d <- readData("pilot-causals-2-trials.csv")
```

## Time

Total time spent on experiment

```{r fig.width=5}
d %>% 
  group_by(workerid) %>% 
  summarize(totalMin = sum(rt/1000/60)) %>%
  ggplot(., aes(x = totalMin))+
  geom_histogram()
```

Time on each trial (first trial in red)

```{r fig.width=5}
d %>%
  ggplot(., aes(x = rt / 1000, fill = trial_num == 0))+
  geom_histogram(position = position_dodge())+
  scale_fill_solarized()+
  xlab("seconds")+
  xlim(0, 200)
```
## Prior and listener data

```{r fig.width=8, fig.height = 3}
df.trials %>%
  filter(condition %in% c("prior", "listener")) %>%
  ggplot(., aes(x = response, fill = condition))+
  #geom_density()+
  geom_histogram(position = position_dodge())+
  facet_grid(.~distribution)+
  scale_fill_grey()+
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1))+
  xlab("causal power / frequency")
```

```{r}
df.listener.summary <- df.trials %>%
  filter(condition %in% c("prior", "listener")) %>%
  mutate(distribution = fct_relevel(distribution, "rare", "accidental", "gendered", "female", "prevalent", "biological")) %>%
  group_by(condition, distribution) %>%
  multi_boot_standard(column = "response")
  
ggplot(df.listener.summary, aes(x = distribution, y = mean, ymin = ci_lower, ymax = ci_upper, fill = condition)) + 
  geom_bar(stat = 'identity', position = position_dodge(), color = 'black')+
  geom_errorbar(position = position_dodge())+
  scale_fill_grey()+
  coord_flip()+
  ylab("mean causal power / frequency")
```

## Speaker data

```{r fig.width=8, fig.height = 3}
df.trials %>%
  filter(condition == "speaker") %>%
  mutate(frequency = factor(frequency),
         distribution = fct_relevel(distribution, "rare", "accidental", "gendered", "female", "prevalent", "biological")) %>%
  ggplot(., aes(x = response, fill = frequency))+
  #geom_density()+
  geom_histogram(position = position_dodge(), bins = 10)+
  facet_grid(distribution~frequency)+
  scale_fill_solarized()+
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1))+
  theme(strip.text.y = element_text(angle = 0))+
  xlab("agreement with causal")
```

```{r}
df.speaker.summary <- df.trials %>%
  filter(condition == "speaker") %>%
  mutate(distribution = fct_relevel(distribution, "rare", "accidental", "gendered", "female", "prevalent", "biological")) %>%
  group_by(condition, distribution, frequency) %>%
  multi_boot_standard(column = "response")
  
ggplot(df.speaker.summary, aes(x = frequency, y = mean, ymin = ci_lower, ymax = ci_upper, fill = distribution)) + 
  geom_bar(stat = 'identity', position = position_dodge(), color = 'black')+
  geom_errorbar(position = position_dodge())+
  scale_fill_solarized()+
  ylab("mean agreement with causal")
```